all: plots/Plot_protrusions_mc.png

data:
	mkdir -p $@ 

plots:
	mkdir -p $@

data/time_success_p280_1.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 280 -s 1 -x 0.2391752577 > $@

data/time_success_p280_2.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 280 -s 2 -x 0.2391752577 > $@

data/time_success_p280_3.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 280 -s 3 -x 0.2391752577 > $@

data/time_success_p280_4.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 280 -s 4 -x 0.2391752577 > $@

data/time_success_p280_5.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 280 -s 5 -x 0.2391752577 > $@

data/time_success_p280_6.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 280 -s 6 -x 0.2391752577 > $@

data/time_success_p280_7.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 280 -s 7 -x 0.2391752577 > $@

data/time_success_p280_8.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 280 -s 8 -x 0.2391752577 > $@

data/time_success_p280_9.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 280 -s 9 -x 0.2391752577 > $@

data/time_success_p280_10.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 280 -s 10 -x 0.2391752577 > $@

data/time_success_p300_1.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 300 -s 1 -x 0.2404447533 > $@

data/time_success_p300_2.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 300 -s 2 -x 0.2404447533 > $@

data/time_success_p300_3.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 300 -s 3 -x 0.2404447533 > $@

data/time_success_p300_4.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 300 -s 4 -x 0.2404447533 > $@

data/time_success_p300_5.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 300 -s 5 -x 0.2404447533 > $@

data/time_success_p300_6.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 300 -s 6 -x 0.2404447533 > $@

data/time_success_p300_7.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 300 -s 7 -x 0.2404447533 > $@

data/time_success_p300_8.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 300 -s 8 -x 0.2404447533 > $@

data/time_success_p300_9.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 300 -s 9 -x 0.2404447533 > $@

data/time_success_p300_10.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 300 -s 10 -x 0.2404447533 > $@

data/time_success_p320_1.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 320 -s 1 -x 0.2404447533 > $@

data/time_success_p320_2.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 320 -s 2 -x 0.2404447533 > $@

data/time_success_p320_3.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 320 -s 3 -x 0.2404447533 > $@

data/time_success_p320_4.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 320 -s 4 -x 0.2404447533 > $@

data/time_success_p320_5.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 320 -s 5 -x 0.2404447533 > $@

data/time_success_p320_6.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 320 -s 6 -x 0.2404447533 > $@

data/time_success_p320_7.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 320 -s 7 -x 0.2404447533 > $@

data/time_success_p320_8.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 320 -s 8 -x 0.2404447533 > $@

data/time_success_p320_9.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 320 -s 9 -x 0.2404447533 > $@

data/time_success_p320_10.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 320 -s 10 -x 0.2404447533 > $@

data/time_success_p340_1.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 340 -s 1 -x 0.2396694215 > $@

data/time_success_p340_2.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 340 -s 2 -x 0.2396694215 > $@

data/time_success_p340_3.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 340 -s 3 -x 0.2396694215 > $@

data/time_success_p340_4.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 340 -s 4 -x 0.2396694215 > $@

data/time_success_p340_5.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 340 -s 5 -x 0.2396694215 > $@

data/time_success_p340_6.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 340 -s 6 -x 0.2396694215 > $@

data/time_success_p340_7.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 340 -s 7 -x 0.2396694215 > $@

data/time_success_p340_8.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 340 -s 8 -x 0.2396694215 > $@

data/time_success_p340_9.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 340 -s 9 -x 0.2396694215 > $@

data/time_success_p340_10.txt: mc_amoeb_kera_log_time_success_standard_sixthmeasured.js | data/
	node $< -p 340 -s 10 -x 0.2396694215 > $@

data/time_success_p280.txt: data/time_success_p280_1.txt data/time_success_p280_2.txt data/time_success_p280_3.txt \
data/time_success_p280_4.txt data/time_success_p280_5.txt data/time_success_p280_6.txt data/time_success_p280_7.txt \
data/time_success_p280_8.txt data/time_success_p280_9.txt data/time_success_p280_10.txt
	cat $? > $@

data/time_success_p300.txt: data/time_success_p300_1.txt data/time_success_p300_2.txt data/time_success_p300_3.txt \
data/time_success_p300_4.txt data/time_success_p300_5.txt data/time_success_p300_6.txt data/time_success_p300_7.txt \
data/time_success_p300_8.txt data/time_success_p300_9.txt data/time_success_p300_10.txt
	cat $? > $@

data/time_success_p320.txt: data/time_success_p320_1.txt data/time_success_p320_2.txt data/time_success_p320_3.txt \
data/time_success_p320_4.txt data/time_success_p320_5.txt data/time_success_p320_6.txt data/time_success_p320_7.txt \
data/time_success_p320_8.txt data/time_success_p320_9.txt data/time_success_p320_10.txt
	cat $? > $@

data/time_success_p340.txt: data/time_success_p340_1.txt data/time_success_p340_2.txt data/time_success_p340_3.txt \
data/time_success_p340_4.txt data/time_success_p340_5.txt data/time_success_p340_6.txt data/time_success_p340_7.txt \
data/time_success_p340_8.txt data/time_success_p340_9.txt data/time_success_p340_10.txt
	cat $? > $@

plots/Plot_protrusions_mc.png: data/time_success_p280.txt data/time_success_p300.txt \
data/time_success_p320.txt data/time_success_p340.txt plots/
	Rscript Plot_time_protrusions.R