all: plots/Plot_mv_mc.png

plots:
	mkdir -p $@

data:
	mkdir -p $@ 

data/mvlog_p280_plot_moore1.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 280 -s 1 > $@

data/mvlog_p280_plot_moore2.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 280 -s 2 > $@

data/mvlog_p280_plot_moore3.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 280 -s 3 > $@

data/mvlog_p280_plot_moore4.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 280 -s 4 > $@

data/mvlog_p280_plot_moore5.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 280 -s 5 > $@

data/mvlog_p280_plot_moore6.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 280 -s 6 > $@

data/mvlog_p280_plot_moore7.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 280 -s 7 > $@

data/mvlog_p280_plot_moore8.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 280 -s 8 > $@

data/mvlog_p280_plot_moore9.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 280 -s 9 > $@

data/mvlog_p280_plot_moore10.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 280 -s 10 > $@

data/mvlog_p300_plot_moore1.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 300 -s 1 > $@

data/mvlog_p300_plot_moore2.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 300 -s 2 > $@

data/mvlog_p300_plot_moore3.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 300 -s 3 > $@

data/mvlog_p300_plot_moore4.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 300 -s 4 > $@

data/mvlog_p300_plot_moore5.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 300 -s 5 > $@

data/mvlog_p300_plot_moore6.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 300 -s 6 > $@

data/mvlog_p300_plot_moore7.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 300 -s 7 > $@

data/mvlog_p300_plot_moore8.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 300 -s 8 > $@

data/mvlog_p300_plot_moore9.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 300 -s 9 > $@

data/mvlog_p300_plot_moore10.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 300 -s 10 > $@

data/mvlog_p320_plot_moore1.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 320 -s 1 > $@

data/mvlog_p320_plot_moore2.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 320 -s 2 > $@

data/mvlog_p320_plot_moore3.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 320 -s 3 > $@

data/mvlog_p320_plot_moore4.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 320 -s 4 > $@

data/mvlog_p320_plot_moore5.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 320 -s 5 > $@

data/mvlog_p320_plot_moore6.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 320 -s 6 > $@

data/mvlog_p320_plot_moore7.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 320 -s 7 > $@

data/mvlog_p320_plot_moore8.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 320 -s 8 > $@

data/mvlog_p320_plot_moore9.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 320 -s 9 > $@

data/mvlog_p320_plot_moore10.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 320 -s 10 > $@

data/mvlog_p340_plot_moore1.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 340 -s 1 > $@

data/mvlog_p340_plot_moore2.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 340 -s 2 > $@

data/mvlog_p340_plot_moore3.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 340 -s 3 > $@

data/mvlog_p340_plot_moore4.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 340 -s 4 > $@

data/mvlog_p340_plot_moore5.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 340 -s 5 > $@

data/mvlog_p340_plot_moore6.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 340 -s 6 > $@

data/mvlog_p340_plot_moore7.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 340 -s 7 > $@

data/mvlog_p340_plot_moore8.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 340 -s 8 > $@

data/mvlog_p340_plot_moore9.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 340 -s 9 > $@

data/mvlog_p340_plot_moore10.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 340 -s 10 > $@

data/mvlog_p360_plot_moore1.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 360 -s 1 > $@

data/mvlog_p360_plot_moore2.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 360 -s 2 > $@

data/mvlog_p360_plot_moore3.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 360 -s 3 > $@

data/mvlog_p360_plot_moore4.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 360 -s 4 > $@

data/mvlog_p360_plot_moore5.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 360 -s 5 > $@

data/mvlog_p360_plot_moore6.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 360 -s 6 > $@

data/mvlog_p360_plot_moore7.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 360 -s 7 > $@

data/mvlog_p360_plot_moore8.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 360 -s 8 > $@

data/mvlog_p360_plot_moore9.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 360 -s 9 > $@

data/mvlog_p360_plot_moore10.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 360 -s 10 > $@

data/mvlog_p380_plot_moore1.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 380 -s 1 > $@

data/mvlog_p380_plot_moore2.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 380 -s 2 > $@

data/mvlog_p380_plot_moore3.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 380 -s 3 > $@

data/mvlog_p380_plot_moore4.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 380 -s 4 > $@

data/mvlog_p380_plot_moore5.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 380 -s 5 > $@

data/mvlog_p380_plot_moore6.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 380 -s 6 > $@

data/mvlog_p380_plot_moore7.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 380 -s 7 > $@

data/mvlog_p380_plot_moore8.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 380 -s 8 > $@

data/mvlog_p380_plot_moore9.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 380 -s 9 > $@

data/mvlog_p380_plot_moore10.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 380 -s 10 > $@

data/mvlog_p400_plot_moore1.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 400 -s 1 > $@

data/mvlog_p400_plot_moore2.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 400 -s 2 > $@

data/mvlog_p400_plot_moore3.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 400 -s 3 > $@

data/mvlog_p400_plot_moore4.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 400 -s 4 > $@

data/mvlog_p400_plot_moore5.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 400 -s 5 > $@

data/mvlog_p400_plot_moore6.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 400 -s 6 > $@

data/mvlog_p400_plot_moore7.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 400 -s 7 > $@

data/mvlog_p400_plot_moore8.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 400 -s 8 > $@

data/mvlog_p400_plot_moore9.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 400 -s 9 > $@

data/mvlog_p400_plot_moore10.txt: standard_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 400 -s 10 > $@

data/mvlog_p280_plot_moore.txt: data/mvlog_p280_plot_moore1.txt data/mvlog_p280_plot_moore2.txt data/mvlog_p280_plot_moore3.txt \
data/mvlog_p280_plot_moore4.txt data/mvlog_p280_plot_moore5.txt data/mvlog_p280_plot_moore6.txt data/mvlog_p280_plot_moore7.txt \
data/mvlog_p280_plot_moore8.txt data/mvlog_p280_plot_moore9.txt data/mvlog_p280_plot_moore10.txt
	cat $? > $@

data/mvlog_p300_plot_moore.txt: data/mvlog_p300_plot_moore1.txt data/mvlog_p300_plot_moore2.txt data/mvlog_p300_plot_moore3.txt \
data/mvlog_p300_plot_moore4.txt data/mvlog_p300_plot_moore5.txt data/mvlog_p300_plot_moore6.txt data/mvlog_p300_plot_moore7.txt \
data/mvlog_p300_plot_moore8.txt data/mvlog_p300_plot_moore9.txt data/mvlog_p300_plot_moore10.txt
	cat $? > $@

data/mvlog_p320_plot_moore.txt: data/mvlog_p320_plot_moore1.txt data/mvlog_p320_plot_moore2.txt data/mvlog_p320_plot_moore3.txt \
data/mvlog_p320_plot_moore4.txt data/mvlog_p320_plot_moore5.txt data/mvlog_p320_plot_moore6.txt data/mvlog_p320_plot_moore7.txt \
data/mvlog_p320_plot_moore8.txt data/mvlog_p320_plot_moore9.txt data/mvlog_p320_plot_moore10.txt
	cat $? > $@

data/mvlog_p340_plot_moore.txt: data/mvlog_p340_plot_moore1.txt data/mvlog_p340_plot_moore2.txt data/mvlog_p340_plot_moore3.txt \
data/mvlog_p340_plot_moore4.txt data/mvlog_p340_plot_moore5.txt data/mvlog_p340_plot_moore6.txt data/mvlog_p340_plot_moore7.txt \
data/mvlog_p340_plot_moore8.txt data/mvlog_p340_plot_moore9.txt data/mvlog_p340_plot_moore10.txt
	cat $? > $@

data/mvlog_p360_plot_moore.txt: data/mvlog_p360_plot_moore1.txt data/mvlog_p360_plot_moore2.txt data/mvlog_p360_plot_moore3.txt \
data/mvlog_p360_plot_moore4.txt data/mvlog_p360_plot_moore5.txt data/mvlog_p360_plot_moore6.txt data/mvlog_p360_plot_moore7.txt \
data/mvlog_p360_plot_moore8.txt data/mvlog_p360_plot_moore9.txt data/mvlog_p360_plot_moore10.txt
	cat $? > $@

data/mvlog_p380_plot_moore.txt: data/mvlog_p380_plot_moore1.txt data/mvlog_p380_plot_moore2.txt data/mvlog_p380_plot_moore3.txt \
data/mvlog_p380_plot_moore4.txt data/mvlog_p380_plot_moore5.txt data/mvlog_p380_plot_moore6.txt data/mvlog_p380_plot_moore7.txt \
data/mvlog_p380_plot_moore8.txt data/mvlog_p380_plot_moore9.txt data/mvlog_p380_plot_moore10.txt
	cat $? > $@

data/mvlog_p400_plot_moore.txt: data/mvlog_p400_plot_moore1.txt data/mvlog_p400_plot_moore2.txt data/mvlog_p400_plot_moore3.txt \
data/mvlog_p400_plot_moore4.txt data/mvlog_p400_plot_moore5.txt data/mvlog_p400_plot_moore6.txt data/mvlog_p400_plot_moore7.txt \
data/mvlog_p400_plot_moore8.txt data/mvlog_p400_plot_moore9.txt data/mvlog_p400_plot_moore10.txt
	cat $? > $@

data/mvlog_p280_plot_sixth_measured1.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 280 -s 1 -x 0.240444753300903 > $@

data/mvlog_p280_plot_sixth_measured2.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 280 -s 2 -x 0.240444753300903 > $@

data/mvlog_p280_plot_sixth_measured3.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 280 -s 3 -x 0.240444753300903 > $@

data/mvlog_p280_plot_sixth_measured4.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 280 -s 4 -x 0.240444753300903 > $@

data/mvlog_p280_plot_sixth_measured5.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 280 -s 5 -x 0.240444753300903 > $@

data/mvlog_p280_plot_sixth_measured6.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 280 -s 6 -x 0.240444753300903 > $@

data/mvlog_p280_plot_sixth_measured7.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 280 -s 7 -x 0.240444753300903 > $@

data/mvlog_p280_plot_sixth_measured8.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 280 -s 8 -x 0.240444753300903 > $@

data/mvlog_p280_plot_sixth_measured9.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 280 -s 9 -x 0.240444753300903 > $@

data/mvlog_p280_plot_sixth_measured10.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 280 -s 10 -x 0.240444753300903 > $@

data/mvlog_p300_plot_sixth_measured1.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 300 -s 1 -x 0.240444753300903 > $@

data/mvlog_p300_plot_sixth_measured2.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 300 -s 2 -x 0.240444753300903 > $@

data/mvlog_p300_plot_sixth_measured3.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 300 -s 3 -x 0.240444753300903 > $@

data/mvlog_p300_plot_sixth_measured4.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 300 -s 4 -x 0.240444753300903 > $@

data/mvlog_p300_plot_sixth_measured5.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 300 -s 5 -x 0.240444753300903 > $@

data/mvlog_p300_plot_sixth_measured6.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 300 -s 6 -x 0.240444753300903 > $@

data/mvlog_p300_plot_sixth_measured7.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 300 -s 7 -x 0.240444753300903 > $@

data/mvlog_p300_plot_sixth_measured8.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 300 -s 8 -x 0.240444753300903 > $@

data/mvlog_p300_plot_sixth_measured9.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 300 -s 9 -x 0.240444753300903 > $@

data/mvlog_p300_plot_sixth_measured10.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 300 -s 10 -x 0.240444753300903 > $@

data/mvlog_p320_plot_sixth_measured1.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 320 -s 1 -x 0.240444753300903 > $@

data/mvlog_p320_plot_sixth_measured2.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 320 -s 2 -x 0.240444753300903 > $@

data/mvlog_p320_plot_sixth_measured3.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 320 -s 3 -x 0.240444753300903 > $@

data/mvlog_p320_plot_sixth_measured4.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 320 -s 4 -x 0.240444753300903 > $@

data/mvlog_p320_plot_sixth_measured5.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 320 -s 5 -x 0.240444753300903 > $@

data/mvlog_p320_plot_sixth_measured6.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 320 -s 6 -x 0.240444753300903 > $@

data/mvlog_p320_plot_sixth_measured7.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 320 -s 7 -x 0.240444753300903 > $@

data/mvlog_p320_plot_sixth_measured8.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 320 -s 8 -x 0.240444753300903 > $@

data/mvlog_p320_plot_sixth_measured9.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 320 -s 9 -x 0.240444753300903 > $@

data/mvlog_p320_plot_sixth_measured10.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 320 -s 10 -x 0.240444753300903 > $@

data/mvlog_p340_plot_sixth_measured1.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 340 -s 1 -x 0.239834596829773 > $@

data/mvlog_p340_plot_sixth_measured2.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 340 -s 2 -x 0.239834596829773 > $@

data/mvlog_p340_plot_sixth_measured3.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 340 -s 3 -x 0.239834596829773 > $@

data/mvlog_p340_plot_sixth_measured4.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 340 -s 4 -x 0.239834596829773 > $@

data/mvlog_p340_plot_sixth_measured5.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 340 -s 5 -x 0.239834596829773 > $@

data/mvlog_p340_plot_sixth_measured6.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 340 -s 6 -x 0.239834596829773 > $@

data/mvlog_p340_plot_sixth_measured7.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 340 -s 7 -x 0.239834596829773 > $@

data/mvlog_p340_plot_sixth_measured8.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 340 -s 8 -x 0.239834596829773 > $@

data/mvlog_p340_plot_sixth_measured9.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 340 -s 9 -x 0.239834596829773 > $@

data/mvlog_p340_plot_sixth_measured10.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 340 -s 10 -x 0.239834596829773 > $@

data/mvlog_p360_plot_sixth_measured1.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 360 -s 1 -x 0.218438050499119 > $@

data/mvlog_p360_plot_sixth_measured2.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 360 -s 2 -x 0.218438050499119 > $@

data/mvlog_p360_plot_sixth_measured3.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 360 -s 3 -x 0.218438050499119 > $@

data/mvlog_p360_plot_sixth_measured4.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 360 -s 4 -x 0.218438050499119 > $@

data/mvlog_p360_plot_sixth_measured5.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 360 -s 5 -x 0.218438050499119 > $@

data/mvlog_p360_plot_sixth_measured6.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 360 -s 6 -x 0.218438050499119 > $@

data/mvlog_p360_plot_sixth_measured7.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 360 -s 7 -x 0.218438050499119 > $@

data/mvlog_p360_plot_sixth_measured8.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 360 -s 8 -x 0.218438050499119 > $@

data/mvlog_p360_plot_sixth_measured9.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 360 -s 9 -x 0.218438050499119 > $@

data/mvlog_p360_plot_sixth_measured10.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 360 -s 10 -x 0.218438050499119 > $@

data/mvlog_p380_plot_sixth_measured1.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 380 -s 1 -x 0.201714573877963 > $@

data/mvlog_p380_plot_sixth_measured2.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 380 -s 2 -x 0.201714573877963 > $@

data/mvlog_p380_plot_sixth_measured3.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 380 -s 3 -x 0.201714573877963 > $@

data/mvlog_p380_plot_sixth_measured4.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 380 -s 4 -x 0.201714573877963 > $@

data/mvlog_p380_plot_sixth_measured5.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 380 -s 5 -x 0.201714573877963 > $@

data/mvlog_p380_plot_sixth_measured6.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 380 -s 6 -x 0.201714573877963 > $@

data/mvlog_p380_plot_sixth_measured7.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 380 -s 7 -x 0.201714573877963 > $@

data/mvlog_p380_plot_sixth_measured8.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 380 -s 8 -x 0.201714573877963 > $@

data/mvlog_p380_plot_sixth_measured9.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 380 -s 9 -x 0.201714573877963 > $@

data/mvlog_p380_plot_sixth_measured10.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 380 -s 10 -x 0.201714573877963 > $@

data/mvlog_p400_plot_sixth_measured1.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 400 -s 1 -x 0.195007065473387 > $@

data/mvlog_p400_plot_sixth_measured2.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 400 -s 2 -x 0.195007065473387 > $@

data/mvlog_p400_plot_sixth_measured3.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 400 -s 3 -x 0.195007065473387 > $@

data/mvlog_p400_plot_sixth_measured4.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 400 -s 4 -x 0.195007065473387 > $@

data/mvlog_p400_plot_sixth_measured5.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 400 -s 5 -x 0.195007065473387 > $@

data/mvlog_p400_plot_sixth_measured6.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 400 -s 6 -x 0.195007065473387 > $@

data/mvlog_p400_plot_sixth_measured7.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 400 -s 7 -x 0.195007065473387 > $@

data/mvlog_p400_plot_sixth_measured8.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 400 -s 8 -x 0.195007065473387 > $@

data/mvlog_p400_plot_sixth_measured9.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 400 -s 9 -x 0.195007065473387 > $@

data/mvlog_p400_plot_sixth_measured10.txt: sixth_perimconstraint_mc_amoeb_kera_log_mv.js | data/
	node $< -p 400 -s 10 -x 0.195007065473387 > $@

data/mvlog_p280_plot_sixth_measured.txt: data/mvlog_p280_plot_sixth_measured1.txt data/mvlog_p280_plot_sixth_measured2.txt data/mvlog_p280_plot_sixth_measured3.txt \
data/mvlog_p280_plot_sixth_measured4.txt data/mvlog_p280_plot_sixth_measured5.txt data/mvlog_p280_plot_sixth_measured6.txt data/mvlog_p280_plot_sixth_measured7.txt \
data/mvlog_p280_plot_sixth_measured8.txt data/mvlog_p280_plot_sixth_measured9.txt data/mvlog_p280_plot_sixth_measured10.txt
	cat $? > $@

data/mvlog_p300_plot_sixth_measured.txt: data/mvlog_p300_plot_sixth_measured1.txt data/mvlog_p300_plot_sixth_measured2.txt data/mvlog_p300_plot_sixth_measured3.txt \
data/mvlog_p300_plot_sixth_measured4.txt data/mvlog_p300_plot_sixth_measured5.txt data/mvlog_p300_plot_sixth_measured6.txt data/mvlog_p300_plot_sixth_measured7.txt \
data/mvlog_p300_plot_sixth_measured8.txt data/mvlog_p300_plot_sixth_measured9.txt data/mvlog_p300_plot_sixth_measured10.txt
	cat $? > $@

data/mvlog_p320_plot_sixth_measured.txt: data/mvlog_p320_plot_sixth_measured1.txt data/mvlog_p320_plot_sixth_measured2.txt data/mvlog_p320_plot_sixth_measured3.txt \
data/mvlog_p320_plot_sixth_measured4.txt data/mvlog_p320_plot_sixth_measured5.txt data/mvlog_p320_plot_sixth_measured6.txt data/mvlog_p320_plot_sixth_measured7.txt \
data/mvlog_p320_plot_sixth_measured8.txt data/mvlog_p320_plot_sixth_measured9.txt data/mvlog_p320_plot_sixth_measured10.txt
	cat $? > $@

data/mvlog_p340_plot_sixth_measured.txt: data/mvlog_p340_plot_sixth_measured1.txt data/mvlog_p340_plot_sixth_measured2.txt data/mvlog_p340_plot_sixth_measured3.txt \
data/mvlog_p340_plot_sixth_measured4.txt data/mvlog_p340_plot_sixth_measured5.txt data/mvlog_p340_plot_sixth_measured6.txt data/mvlog_p340_plot_sixth_measured7.txt \
data/mvlog_p340_plot_sixth_measured8.txt data/mvlog_p340_plot_sixth_measured9.txt data/mvlog_p340_plot_sixth_measured10.txt
	cat $? > $@

data/mvlog_p360_plot_sixth_measured.txt: data/mvlog_p360_plot_sixth_measured1.txt data/mvlog_p360_plot_sixth_measured2.txt data/mvlog_p360_plot_sixth_measured3.txt \
data/mvlog_p360_plot_sixth_measured4.txt data/mvlog_p360_plot_sixth_measured5.txt data/mvlog_p360_plot_sixth_measured6.txt data/mvlog_p360_plot_sixth_measured7.txt \
data/mvlog_p360_plot_sixth_measured8.txt data/mvlog_p360_plot_sixth_measured9.txt data/mvlog_p360_plot_sixth_measured10.txt
	cat $? > $@

data/mvlog_p380_plot_sixth_measured.txt: data/mvlog_p380_plot_sixth_measured1.txt data/mvlog_p380_plot_sixth_measured2.txt data/mvlog_p380_plot_sixth_measured3.txt \
data/mvlog_p380_plot_sixth_measured4.txt data/mvlog_p380_plot_sixth_measured5.txt data/mvlog_p380_plot_sixth_measured6.txt data/mvlog_p380_plot_sixth_measured7.txt \
data/mvlog_p380_plot_sixth_measured8.txt data/mvlog_p380_plot_sixth_measured9.txt data/mvlog_p380_plot_sixth_measured10.txt
	cat $? > $@

data/mvlog_p400_plot_sixth_measured.txt: data/mvlog_p400_plot_sixth_measured1.txt data/mvlog_p400_plot_sixth_measured2.txt data/mvlog_p400_plot_sixth_measured3.txt \
data/mvlog_p400_plot_sixth_measured4.txt data/mvlog_p400_plot_sixth_measured5.txt data/mvlog_p400_plot_sixth_measured6.txt data/mvlog_p400_plot_sixth_measured7.txt \
data/mvlog_p400_plot_sixth_measured8.txt data/mvlog_p400_plot_sixth_measured9.txt data/mvlog_p400_plot_sixth_measured10.txt
	cat $? > $@

plots/Plot_mv_mc.png: data/mvlog_p280_plot_moore.txt data/mvlog_p300_plot_moore.txt \
data/mvlog_p320_plot_moore.txt data/mvlog_p340_plot_moore.txt \
data/mvlog_p360_plot_moore.txt data/mvlog_p380_plot_moore.txt \
data/mvlog_p400_plot_moore.txt \
data/mvlog_p280_plot_sixth_measured.txt data/mvlog_p300_plot_sixth_measured.txt \
data/mvlog_p320_plot_sixth_measured.txt data/mvlog_p340_plot_sixth_measured.txt \
data/mvlog_p360_plot_sixth_measured.txt data/mvlog_p380_plot_sixth_measured.txt \
data/mvlog_p400_plot_sixth_measured.txt plots/
	Rscript Plot_mv_mc.R