all: data/all-res-p70.txt plots/Plot_sorting_finishtime.png plots/Final_plot_interfaces_time.png

plots:
	mkdir -p $@

data:
	mkdir -p $@ 

data/res1.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 1 > $@

data/res2.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 4 > $@

data/res3.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 6 > $@

data/res4.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 10 > $@

data/res5.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 11 > $@

data/res6.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 12 > $@

data/res7.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 14 > $@

data/res8.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 19 > $@

data/res9.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 33 > $@

data/res10.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 34 > $@

data/res11.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 36 > $@

data/res12.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 39 > $@

data/res13.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 44 > $@

data/res14.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 46 > $@

data/res15.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 47 > $@

data/res16.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 48 > $@

data/res17.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 49 > $@

data/res18.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 52 > $@

data/res19.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 53 > $@

data/res20.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 54 > $@

data/res21.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 62 > $@

data/res22.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 65 > $@

data/res23.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 66 > $@

data/res24.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 67 > $@

data/res25.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 69 > $@

data/res26.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 71 > $@

data/res27.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 74 > $@

data/res28.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 76 > $@

data/res29.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 77 > $@

data/res30.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 80 > $@

data/res31.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 81 > $@

data/res32.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 83 > $@

data/res33.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 88 > $@

data/res34.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 91 > $@

data/res35.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 94 > $@

data/res36.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 97 > $@

data/res37.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 101 > $@

data/res38.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 102 > $@

data/res39.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 103 > $@

data/res40.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 107 > $@

data/res41.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 108 > $@

data/res42.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 109 > $@

data/res43.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 111 > $@

data/res44.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 113 > $@

data/res45.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 114 > $@

data/res46.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 116 > $@

data/res47.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 118 > $@

data/res48.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 122 > $@

data/res49.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 123 > $@

data/res50.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 70 -x 0.1776 -s 128 > $@

runs=1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 \
31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50

data/all-res-p70.txt : $(foreach c, $(runs), data/res$(c).txt) | data/res50.txt
	cat $^ > $@

data/res1_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 1 > $@

data/res2_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 4 > $@

data/res3_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 6 > $@

data/res4_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 10 > $@

data/res5_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 11 > $@

data/res6_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 12 > $@

data/res7_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 14 > $@

data/res8_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 19 > $@

data/res9_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 33 > $@

data/res10_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 34 > $@

data/res11_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 36 > $@

data/res12_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 39 > $@

data/res13_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 44 > $@

data/res14_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 46 > $@

data/res15_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 47 > $@

data/res16_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 48 > $@

data/res17_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 49 > $@

data/res18_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 52 > $@

data/res19_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 53 > $@

data/res20_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 54 > $@

data/res21_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 62 > $@

data/res22_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 65 > $@

data/res23_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 66 > $@

data/res24_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 67 > $@

data/res25_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 69 > $@

data/res26_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 71 > $@

data/res27_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 74 > $@

data/res28_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 76 > $@

data/res29_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 77 > $@

data/res30_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 80 > $@

data/res31_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 81 > $@

data/res32_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 83 > $@

data/res33_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 88 > $@

data/res34_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 91 > $@

data/res35_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 94 > $@

data/res36_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 97 > $@

data/res37_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 101 > $@

data/res38_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 102 > $@

data/res39_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 103 > $@

data/res40_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 107 > $@

data/res41_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 108 > $@

data/res42_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 109 > $@

data/res43_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 111 > $@

data/res44_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 113 > $@

data/res45_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 114 > $@

data/res46_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 116 > $@

data/res47_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 118 > $@

data/res48_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 122 > $@

data/res49_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 123 > $@

data/res50_p100.txt: Cell_sorting_neighborhoods_log_time_completion.js | data/
	node $< -p 100 -x 0.206 -s 128 > $@

runs=1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 \
31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50

data/all-res-p100.txt : $(foreach c, $(runs), data/res$(c)_p100.txt) | data/res50_p100.txt
	cat $^ > $@

data/res_log_interfaces.txt : Cell_sorting_neighborhoods_log_interfaces.js | data/
	node $< -p 70 -x 0.1776 -s 1 > $@

plots/Plot_sorting_finishtime.png : Plot_sorting_finishtime.R data/all-res-p70.txt | plots/
	Rscript $<

plots/Final_plot_interfaces_time.png : Plot_sorting_finishtime.R | data/res_log_interfaces.txt
	Rscript $<
